/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Mehak
 */
public class SimpleCalculator extends javax.swing.JFrame {

    /**
     * Creates new form SimpleCalculator
     */
    Calculator cc=new Calculator();
    public SimpleCalculator() {
        initComponents();
        disable();
         buttonGroup1.add(onrad);
        buttonGroup1.add(offrad);
        panesc.setVisible(false);
          this.setSize(240, 420);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        scbut = new javax.swing.JButton();
        panesimple = new javax.swing.JLayeredPane();
        clearbutton = new javax.swing.JButton();
        dltbutton = new javax.swing.JButton();
        plusbutton = new javax.swing.JButton();
        onebutton = new javax.swing.JButton();
        twobutton = new javax.swing.JButton();
        threebutton = new javax.swing.JButton();
        minusbutton = new javax.swing.JButton();
        multiplybutton = new javax.swing.JButton();
        sixbutton = new javax.swing.JButton();
        fivebutton = new javax.swing.JButton();
        fourbutton = new javax.swing.JButton();
        sevenbutton = new javax.swing.JButton();
        eightbutton = new javax.swing.JButton();
        ninebutton = new javax.swing.JButton();
        dividebutton = new javax.swing.JButton();
        equalbutton = new javax.swing.JButton();
        plusminusbutton = new javax.swing.JButton();
        zerobutton = new javax.swing.JButton();
        dotbutton = new javax.swing.JButton();
        onrad = new javax.swing.JRadioButton();
        offrad = new javax.swing.JRadioButton();
        screenfield = new javax.swing.JTextField();
        panesc = new javax.swing.JLayeredPane();
        cotbutton = new javax.swing.JButton();
        tanbutton = new javax.swing.JButton();
        sinbutton = new javax.swing.JButton();
        cosbutton = new javax.swing.JButton();
        logbutton = new javax.swing.JButton();
        radicalbutton = new javax.swing.JButton();
        powerbutton = new javax.swing.JButton();
        exbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        simplebutton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        scbut.setText("Scientific");
        scbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scbutActionPerformed(evt);
            }
        });

        clearbutton.setBackground(new java.awt.Color(153, 153, 153));
        clearbutton.setText("C");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        dltbutton.setBackground(new java.awt.Color(153, 153, 153));
        dltbutton.setText("⌫ ");
        dltbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbuttonActionPerformed(evt);
            }
        });

        plusbutton.setBackground(new java.awt.Color(153, 153, 153));
        plusbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plusbutton.setText("+");
        plusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbuttonActionPerformed(evt);
            }
        });

        onebutton.setBackground(new java.awt.Color(153, 153, 153));
        onebutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        onebutton.setText("1");
        onebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onebuttonActionPerformed(evt);
            }
        });

        twobutton.setBackground(new java.awt.Color(153, 153, 153));
        twobutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        twobutton.setText("2");
        twobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twobuttonActionPerformed(evt);
            }
        });

        threebutton.setBackground(new java.awt.Color(153, 153, 153));
        threebutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        threebutton.setText("3");
        threebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threebuttonActionPerformed(evt);
            }
        });

        minusbutton.setBackground(new java.awt.Color(153, 153, 153));
        minusbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minusbutton.setText("-");
        minusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbuttonActionPerformed(evt);
            }
        });

        multiplybutton.setBackground(new java.awt.Color(153, 153, 153));
        multiplybutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        multiplybutton.setText("×");
        multiplybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplybuttonActionPerformed(evt);
            }
        });

        sixbutton.setBackground(new java.awt.Color(153, 153, 153));
        sixbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sixbutton.setText("6");
        sixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixbuttonActionPerformed(evt);
            }
        });

        fivebutton.setBackground(new java.awt.Color(153, 153, 153));
        fivebutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fivebutton.setText("5");
        fivebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebuttonActionPerformed(evt);
            }
        });

        fourbutton.setBackground(new java.awt.Color(153, 153, 153));
        fourbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fourbutton.setText("4");
        fourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourbuttonActionPerformed(evt);
            }
        });

        sevenbutton.setBackground(new java.awt.Color(153, 153, 153));
        sevenbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sevenbutton.setText("7");
        sevenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbuttonActionPerformed(evt);
            }
        });

        eightbutton.setBackground(new java.awt.Color(153, 153, 153));
        eightbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        eightbutton.setText("8");
        eightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightbuttonActionPerformed(evt);
            }
        });

        ninebutton.setBackground(new java.awt.Color(153, 153, 153));
        ninebutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ninebutton.setText("9");
        ninebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninebuttonActionPerformed(evt);
            }
        });

        dividebutton.setBackground(new java.awt.Color(153, 153, 153));
        dividebutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dividebutton.setText("÷ ");
        dividebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividebuttonActionPerformed(evt);
            }
        });

        equalbutton.setBackground(new java.awt.Color(153, 153, 153));
        equalbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        equalbutton.setText("=");
        equalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalbuttonActionPerformed(evt);
            }
        });

        plusminusbutton.setBackground(new java.awt.Color(153, 153, 153));
        plusminusbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plusminusbutton.setText("+/-");
        plusminusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusbuttonActionPerformed(evt);
            }
        });

        zerobutton.setBackground(new java.awt.Color(153, 153, 153));
        zerobutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        zerobutton.setText("0");
        zerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobuttonActionPerformed(evt);
            }
        });

        dotbutton.setBackground(new java.awt.Color(153, 153, 153));
        dotbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dotbutton.setText(".");
        dotbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotbuttonActionPerformed(evt);
            }
        });

        onrad.setText("ON");
        onrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onradActionPerformed(evt);
            }
        });

        offrad.setText("OFF");
        offrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offradActionPerformed(evt);
            }
        });

        screenfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cotbutton.setBackground(new java.awt.Color(153, 153, 153));
        cotbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cotbutton.setText("Cosh");
        cotbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotbuttonActionPerformed(evt);
            }
        });

        tanbutton.setBackground(new java.awt.Color(153, 153, 153));
        tanbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tanbutton.setText("Tan");
        tanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanbuttonActionPerformed(evt);
            }
        });

        sinbutton.setBackground(new java.awt.Color(153, 153, 153));
        sinbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sinbutton.setText("Sin");
        sinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinbuttonActionPerformed(evt);
            }
        });

        cosbutton.setBackground(new java.awt.Color(153, 153, 153));
        cosbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cosbutton.setText("Cos");
        cosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosbuttonActionPerformed(evt);
            }
        });

        logbutton.setBackground(new java.awt.Color(153, 153, 153));
        logbutton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logbutton.setText("Log");
        logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttonActionPerformed(evt);
            }
        });

        radicalbutton.setBackground(new java.awt.Color(153, 153, 153));
        radicalbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radicalbutton.setText("√ ");
        radicalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radicalbuttonActionPerformed(evt);
            }
        });

        powerbutton.setBackground(new java.awt.Color(153, 153, 153));
        powerbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        powerbutton.setText("x²");
        powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerbuttonActionPerformed(evt);
            }
        });

        exbutton.setBackground(new java.awt.Color(153, 153, 153));
        exbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exbutton.setText("x³");
        exbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setText("Scientific Operations");

        panesc.setLayer(cotbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(tanbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(sinbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(cosbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(logbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(radicalbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(powerbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(exbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesc.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panescLayout = new javax.swing.GroupLayout(panesc);
        panesc.setLayout(panescLayout);
        panescLayout.setHorizontalGroup(
            panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panescLayout.createSequentialGroup()
                .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panescLayout.createSequentialGroup()
                        .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sinbutton)
                                .addComponent(tanbutton))
                            .addComponent(logbutton)
                            .addComponent(powerbutton))
                        .addGap(18, 18, 18)
                        .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exbutton)
                            .addComponent(radicalbutton)
                            .addComponent(cosbutton)
                            .addComponent(cotbutton)))
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panescLayout.setVerticalGroup(
            panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panescLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinbutton)
                    .addComponent(cosbutton))
                .addGap(18, 18, 18)
                .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanbutton)
                    .addComponent(cotbutton))
                .addGap(18, 18, 18)
                .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logbutton)
                    .addComponent(radicalbutton))
                .addGap(18, 18, 18)
                .addGroup(panescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerbutton)
                    .addComponent(exbutton))
                .addContainerGap())
        );

        panesimple.setLayer(clearbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(dltbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(plusbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(onebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(twobutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(threebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(minusbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(multiplybutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(sixbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(fivebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(fourbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(sevenbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(eightbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(ninebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(dividebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(equalbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(plusminusbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(zerobutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(dotbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(onrad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(offrad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(screenfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panesimple.setLayer(panesc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panesimpleLayout = new javax.swing.GroupLayout(panesimple);
        panesimple.setLayout(panesimpleLayout);
        panesimpleLayout.setHorizontalGroup(
            panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panesimpleLayout.createSequentialGroup()
                .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(screenfield, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panesimpleLayout.createSequentialGroup()
                            .addComponent(onrad)
                            .addGap(18, 18, 18)
                            .addComponent(offrad))
                        .addGroup(panesimpleLayout.createSequentialGroup()
                            .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panesimpleLayout.createSequentialGroup()
                                    .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fourbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dotbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sevenbutton, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fivebutton)
                                        .addComponent(eightbutton)
                                        .addGroup(panesimpleLayout.createSequentialGroup()
                                            .addComponent(zerobutton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(plusminusbutton))))
                                .addGroup(panesimpleLayout.createSequentialGroup()
                                    .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panesimpleLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(clearbutton))
                                        .addGroup(panesimpleLayout.createSequentialGroup()
                                            .addComponent(onebutton)
                                            .addGap(18, 18, 18)
                                            .addComponent(twobutton)))
                                    .addGap(18, 18, 18)
                                    .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(threebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dltbutton)
                                        .addComponent(sixbutton)
                                        .addComponent(ninebutton))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(multiplybutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dividebutton)
                                .addComponent(minusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(equalbutton)))))
                .addGap(18, 18, 18)
                .addComponent(panesc)
                .addContainerGap())
        );
        panesimpleLayout.setVerticalGroup(
            panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panesimpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onrad)
                    .addComponent(offrad))
                .addGap(18, 18, 18)
                .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panesimpleLayout.createSequentialGroup()
                        .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearbutton)
                            .addComponent(dltbutton))
                        .addGap(18, 18, 18)
                        .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onebutton)
                            .addComponent(twobutton))
                        .addGap(18, 18, 18)
                        .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourbutton)
                            .addComponent(fivebutton)
                            .addComponent(sixbutton))
                        .addGap(18, 18, 18)
                        .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenbutton)
                            .addComponent(eightbutton)
                            .addComponent(ninebutton)))
                    .addGroup(panesimpleLayout.createSequentialGroup()
                        .addComponent(plusbutton)
                        .addGap(18, 18, 18)
                        .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minusbutton)
                            .addComponent(threebutton))
                        .addGap(18, 18, 18)
                        .addComponent(multiplybutton)
                        .addGap(18, 18, 18)
                        .addComponent(dividebutton)))
                .addGap(18, 18, 18)
                .addGroup(panesimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotbutton)
                    .addComponent(zerobutton)
                    .addComponent(plusminusbutton)
                    .addComponent(equalbutton))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panesimpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        simplebutton.setText("simple");
        simplebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panesimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scbut)
                        .addGap(18, 18, 18)
                        .addComponent(simplebutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scbut)
                    .addComponent(simplebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panesimple)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String one;
String two;
String three;
String four;
String five;
String six;
String seven;
String eight;
String nine;
String zero;
String dot;
String equal;
String plus;
String minus;
String multiply;
String divide;
String sin;
String cos;
String tan;
String cot;
String radical;
String square;
String ex;
String log;
String on;
String off;
String onenumber;
String twonumber;
String result;
 double firstnum;
     double secondnum;
      double outp;
      String operations;
      private Object math; 

 public void enable(){
        screenfield.setEnabled(true);
        onebutton.setEnabled(true);
        twobutton.setEnabled(true);
        threebutton.setEnabled(true);
        fourbutton.setEnabled(true);
        fivebutton.setEnabled(true);
        sixbutton.setEnabled(true);
        sevenbutton.setEnabled(true);
        eightbutton.setEnabled(true);
        ninebutton.setEnabled(true);
        zerobutton.setEnabled(true);
        sinbutton.setEnabled(true);
        cosbutton.setEnabled(true);
        tanbutton.setEnabled(true);
        cotbutton.setEnabled(true);
        radicalbutton.setEnabled(true);
        exbutton.setEnabled(true);
        dotbutton.setEnabled(true);
        powerbutton.setEnabled(true);
        plusbutton.setEnabled(true);
        minusbutton.setEnabled(true);
        dividebutton.setEnabled(true);
        multiplybutton.setEnabled(true);
        equalbutton.setEnabled(true);
        logbutton.setEnabled(true);
        plusminusbutton.setEnabled(true);
        dltbutton.setEnabled(true);
         clearbutton.setEnabled(true);
         simplebutton.setEnabled(true);
         scbut.setEnabled(true);
        }
 public void disable(){
        screenfield.setEnabled(false);
        onebutton.setEnabled(false);
        twobutton.setEnabled(false);
        threebutton.setEnabled(false);
        fourbutton.setEnabled(false);
        fivebutton.setEnabled(false);
        sixbutton.setEnabled(false);
        sevenbutton.setEnabled(false);
        eightbutton.setEnabled(false);
        ninebutton.setEnabled(false);
        zerobutton.setEnabled(false);
        sinbutton.setEnabled(false);
        cosbutton.setEnabled(false);
        tanbutton.setEnabled(false);
        cotbutton.setEnabled(false);
        radicalbutton.setEnabled(false);
        exbutton.setEnabled(false);
        dotbutton.setEnabled(false);
        powerbutton.setEnabled(false);
        plusbutton.setEnabled(false);
        minusbutton.setEnabled(false);
        dividebutton.setEnabled(false);
        multiplybutton.setEnabled(false);
        equalbutton.setEnabled(false);
        logbutton.setEnabled(false);
         plusminusbutton.setEnabled(false);
         dltbutton.setEnabled(false);
         clearbutton.setEnabled(false);
         simplebutton.setEnabled(false);
         scbut.setEnabled(false);
 }

    private void onebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onebuttonActionPerformed
       
             one=screenfield.getText()+onebutton.getText();
             screenfield.setText(one);

    
     
        
    }//GEN-LAST:event_onebuttonActionPerformed

    private void twobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twobuttonActionPerformed
        // TODO add your handling code here:
              two=screenfield.getText()+twobutton.getText();
             screenfield.setText(two);
    }//GEN-LAST:event_twobuttonActionPerformed

    private void threebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threebuttonActionPerformed
        // TODO add your handling code here:
        three=screenfield.getText()+threebutton.getText();
             screenfield.setText(three);
    }//GEN-LAST:event_threebuttonActionPerformed

    private void fourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourbuttonActionPerformed
        // TODO add your handling code here:
         four=screenfield.getText()+fourbutton.getText();
             screenfield.setText(four);
    }//GEN-LAST:event_fourbuttonActionPerformed

    private void fivebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebuttonActionPerformed
        // TODO add your handling code here:
        five=screenfield.getText()+fivebutton.getText();
             screenfield.setText(five);
    }//GEN-LAST:event_fivebuttonActionPerformed

    private void sixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixbuttonActionPerformed
        // TODO add your handling code here:
        six=screenfield.getText()+sixbutton.getText();
             screenfield.setText(six);
    }//GEN-LAST:event_sixbuttonActionPerformed

    private void sevenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbuttonActionPerformed
        // TODO add your handling code here:
         seven=screenfield.getText()+sevenbutton.getText();
             screenfield.setText(seven);
    }//GEN-LAST:event_sevenbuttonActionPerformed

    private void eightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightbuttonActionPerformed
        // TODO add your handling code here:
        eight=screenfield.getText()+eightbutton.getText();
             screenfield.setText(eight);
    }//GEN-LAST:event_eightbuttonActionPerformed

    private void ninebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninebuttonActionPerformed
        // TODO add your handling code here:
         nine=screenfield.getText()+ninebutton.getText();
             screenfield.setText(nine);
    }//GEN-LAST:event_ninebuttonActionPerformed

    private void dotbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotbuttonActionPerformed
        // TODO add your handling code here:
      if(!screenfield.getText().contains("."))
            screenfield.setText(screenfield.getText()+dotbutton.getText());
    }//GEN-LAST:event_dotbuttonActionPerformed

    private void zerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobuttonActionPerformed
        // TODO add your handling code here:
        zero=screenfield.getText()+zerobutton.getText();
             screenfield.setText(zero);
    }//GEN-LAST:event_zerobuttonActionPerformed

    private void equalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalbuttonActionPerformed
        // TODO add your handling code here:
         String answer;
        secondnum = Double.parseDouble(screenfield.getText());
        if(operations=="+")
        {
        outp=firstnum+secondnum;
        answer = String.format("%.2f", outp);
        screenfield.setText(answer);
        }
        
        else if(operations=="-")
        {
        outp=firstnum-secondnum;
        answer = String.format("%.2f", outp);
        screenfield.setText(answer);
        }
       else if(operations=="*")
        {
        outp=firstnum*secondnum;
        answer = String.format("%.2f", outp);
        screenfield.setText(answer);
        }
        else if(operations=="/")
        {
        outp=firstnum/secondnum;
        answer = String.format("%.2f", outp);
        screenfield.setText(answer);
        }
        else if(operations=="%")
        {
        outp=firstnum%secondnum;
        answer = String.format("%.2f", outp);
        screenfield.setText(answer);
        }
       
      
    }//GEN-LAST:event_equalbuttonActionPerformed

    private void plusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbuttonActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(screenfield.getText());
        screenfield.setText(null);
        operations=("+");
    }//GEN-LAST:event_plusbuttonActionPerformed

    private void minusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbuttonActionPerformed
        // TODO add your handling code here:
          firstnum = Double.parseDouble(screenfield.getText());
        screenfield.setText(null);
        operations=("-");
    }//GEN-LAST:event_minusbuttonActionPerformed

    private void multiplybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplybuttonActionPerformed
        // TODO add your handling code here:
    firstnum = Double.parseDouble(screenfield.getText());
        screenfield.setText(null);
        operations=("*");
    }//GEN-LAST:event_multiplybuttonActionPerformed

    private void dividebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividebuttonActionPerformed
        // TODO add your handling code here:
          firstnum = Double.parseDouble(screenfield.getText());
        screenfield.setText(null);
        operations=("/");
    }//GEN-LAST:event_dividebuttonActionPerformed

    private void sinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinbuttonActionPerformed
    double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.sin(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_sinbuttonActionPerformed

    private void cosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosbuttonActionPerformed
        // TODO add your handling code here:
        double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.cos(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_cosbuttonActionPerformed

    private void tanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanbuttonActionPerformed
        // TODO add your handling code here:
       double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.tan(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_tanbuttonActionPerformed

    private void cotbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotbuttonActionPerformed
        // TODO add your handling code here:
         double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.cosh(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_cotbuttonActionPerformed

    private void powerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerbuttonActionPerformed
        // TODO add your handling code here:
          double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=(scnc*scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_powerbuttonActionPerformed

    private void exbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exbuttonActionPerformed
        // TODO add your handling code here:
      ex=screenfield.getText()+exbutton.getText();
             screenfield.setText(ex);
    }//GEN-LAST:event_exbuttonActionPerformed

    private void radicalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radicalbuttonActionPerformed
        // TODO add your handling code here:
      double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.sqrt(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_radicalbuttonActionPerformed

    private void logbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbuttonActionPerformed
   double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=Math.log(scnc);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_logbuttonActionPerformed

    private void onradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onradActionPerformed
        // TODO add your handling code here:
        on=onrad.getText();
        
           enable();
     
        
    }//GEN-LAST:event_onradActionPerformed

    private void offradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offradActionPerformed
        // TODO add your handling code here:
        off=offrad.getText();
       disable();
    }//GEN-LAST:event_offradActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        screenfield.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void plusminusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusbuttonActionPerformed
        // TODO add your handling code here:
         double scnc=Double.parseDouble(String.valueOf(screenfield.getText()));
        scnc=scnc*(-1);
        screenfield.setText(String.valueOf(scnc));
    }//GEN-LAST:event_plusminusbuttonActionPerformed

    private void scbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scbutActionPerformed
        // TODO add your handling code here:
         panesc.setVisible(true);
          this.setResizable(true);
         this.setSize(410, 420);
        
        
        
        
        
    }//GEN-LAST:event_scbutActionPerformed

    private void dltbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbuttonActionPerformed
        // TODO add your handling code here:
                String dlt=null;
        if(screenfield.getText().length()>0)
        {
        StringBuilder SB =new StringBuilder(screenfield.getText());
        SB.deleteCharAt(screenfield.getText().length()-1);
        dlt=SB.toString();
        screenfield.setText(dlt);}
    }//GEN-LAST:event_dltbuttonActionPerformed

    private void simplebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplebuttonActionPerformed
        // TODO add your handling code here:
               simplebutton.setVisible(true);
                      panesc.setVisible(false);
          this.setResizable(true);
           this.setSize(240, 420);
    }//GEN-LAST:event_simplebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton cosbutton;
    private javax.swing.JButton cotbutton;
    private javax.swing.JButton dividebutton;
    private javax.swing.JButton dltbutton;
    private javax.swing.JButton dotbutton;
    private javax.swing.JButton eightbutton;
    private javax.swing.JButton equalbutton;
    private javax.swing.JButton exbutton;
    private javax.swing.JButton fivebutton;
    private javax.swing.JButton fourbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logbutton;
    private javax.swing.JButton minusbutton;
    private javax.swing.JButton multiplybutton;
    private javax.swing.JButton ninebutton;
    private javax.swing.JRadioButton offrad;
    private javax.swing.JButton onebutton;
    private javax.swing.JRadioButton onrad;
    private javax.swing.JLayeredPane panesc;
    private javax.swing.JLayeredPane panesimple;
    private javax.swing.JButton plusbutton;
    private javax.swing.JButton plusminusbutton;
    private javax.swing.JButton powerbutton;
    private javax.swing.JButton radicalbutton;
    private javax.swing.JButton scbut;
    private javax.swing.JTextField screenfield;
    private javax.swing.JButton sevenbutton;
    private javax.swing.JButton simplebutton;
    private javax.swing.JButton sinbutton;
    private javax.swing.JButton sixbutton;
    private javax.swing.JButton tanbutton;
    private javax.swing.JButton threebutton;
    private javax.swing.JButton twobutton;
    private javax.swing.JButton zerobutton;
    // End of variables declaration//GEN-END:variables
}
